%strFile='D:\GraStuCor\EleMolCloud\Molecule\宁利超1\A\A1.dst';
strFile='D:\GraStuCor\EleMolCloud\Molecule\宁利超1\B\B1.dst';
[ Atom_info,AtomNum, ElecCloudDenNum, CubePoints, step_num, step, org_coor ] = Func_GetCubePoints( strFile );
load LUT.mat
step_1=step_num(1);
step_2=step_num(2);
step_3=step_num(3);
tic;
[vX,vY,vZ,vFace]=Func_GetAllBoundaries_And_Interpolation(CubePoints, step_1, step_2, step_3, LUT);
vX=vX+10;
time1=toc;
fprintf('代码段1执行时间: %f 秒\n', time1);
%[  vX, vY, vZ, iLen, iFace, vFace ] = Func_ContourV2( CubePoints, step_1, step_2, step_3, LUT  );
iLen = length(vX);
iFace = length(vFace);
% % 
dir='D:\GraStuCor\EleMolCloud\Plot Geomagic Wrap\';
% if b==1
%     dir1='nlc2x';
% elseif b==2
%     dir1='nlc2y';
% else
%     dir1='nlc2z';
% end
% filename=strcat(dir,dir1,num2str(c),'.ply');
dir1='B1dst_0';
filename=strcat(dir,dir1,'.ply');
fid = fopen(filename, 'wt');
fprintf(fid,'ply\n');
fprintf(fid,'format ascii 1.0\n');
fprintf(fid,'comment generated by ply_writer\n');
fprintf(fid,'element vertex %d\n', iLen);
fprintf(fid,'property float x\n');
fprintf(fid,'property float y\n');
fprintf(fid,'property float z\n');
fprintf(fid,'element face %d\n', iFace);
fprintf(fid,'property list uchar int vertex_indices\n');
fprintf(fid,'end_header\n');
for i = 1 : iLen
    fprintf(fid, '%8.6f %8.6f %8.6f\n', vX(i),  vY(i),  vZ(i));
end
for i = 1 : iFace
    fprintf(fid,'%d %d %d %d\n', 3, vFace(i, 1)-1, vFace(i, 2) - 1, vFace(i, 3) - 1);
end
fclose(fid);
  